name: flutter_redux_mall
description: A Flutter Mall application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fish_redux: ^0.1.6
  toast: ^0.1.3
  common_utils: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

# assets begin
# images/*
    - images/avatar_default.png
    - images/back.png
    - images/back_white.png
    - images/banner_indicator_nor.png
    - images/banner_indicator_sel.png
    - images/empty_banner.png
    - images/empty_small.png
    - images/home_discount.png
    - images/home_good.png
    - images/home_integral.png
    - images/home_new.png
    - images/icon_rhombus.png
    - images/login_qq.png
    - images/login_sina.png
    - images/login_weixin.png
    - images/my_address.png
    - images/my_background.png
    - images/my_balance.png
    - images/my_collection.png
    - images/my_coupon.png
    - images/my_news.png
    - images/my_opinion.png
    - images/my_points.png
    - images/my_promote.png
    - images/my_service.png
    - images/my_setting.png
    - images/my_tracks.png
    - images/next.png
    - images/next_white.png
    - images/not_selected.png
    - images/no_shoppingcart.png
    - images/plus.png
    - images/reduce.png
    - images/refund.png
    - images/search_black.png
    - images/selected.png
    - images/shopping_cart_fold.png
    - images/tab_category_nor.png
    - images/tab_category_sel.png
    - images/tab_home_nor.png
    - images/tab_home_sel.png
    - images/tab_mine_nor.png
    - images/tab_mine_sel.png
    - images/tab_shoppingcart_nor.png
    - images/tab_shoppingcart_sel.png
    - images/wait_evaluate.png
    - images/wait_pay.png
    - images/wait_receive.png
    - images/wait_send.png
# assets end
